### ISSUE TITLE
Acceleration values?

### ISSUE THREAD

**Issue by DrBwts** [plasmapper/adxl355-arduino#2]
I notice you divide the raw values by 4096 then multiply by the scale factor.

How did you arrive at the acceleration scale factors?

**Comment by plasmapper** [comment]
Accelerations are copied from the 3 bytes of the ADXL355 memory (where they are shifted 4 bits to the left) to the higher 4 bytes of int32 (where they are now shifted 12 bits to the left, forming correct signed integers just 4096 times larger than they should be).
Acceleration scale factors in g/LSB are taken from the ADXL355 datasheet.

**Comment by DrBwts** [comment]
Thankyou, makes sense now.
