### ISSUE TITLE
Self test result is different

### ISSUE THREAD

**Issue by edmfiedler** [plasmapper/adxl355-arduino#3]
I'm evaluating the sensor using your self-test program. I have been getting the same result with different arduinos on different sensors, but they are different to your suggested IDs and acceleration values.

**Comment by plasmapper** [comment]
That's strange. I tested it again (I only have [Arduino Due](https://docs.arduino.cc/hardware/due) and [EVAL-ADXL355-PMDZ](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/EVAL-ADXL355-PMDZ.html)). This is what I get:
```Vendor ID (should be 0xAD): 0xAD
Family ID (should be 0x1D): 0x1D
Device ID (should be 0xED): 0xED
Revision ID: 0x1

Self test (should be 0.1...0.6 g, 0.1...0.6 g, 0.5...3.0 g): 0.34, 0.34, 1.41
```
What is your output?

**Comment by edmfiedler** [comment]
Thanks, I have now been able to get the same output as well. I was using the 3.3V pin and the wrong chip select pin.

However, I would like to note that I only get the same output as you suggest when I unplug the arduino and plug it back in. If I simply press the reset button, there seems to be some interference with the communication.

**Comment by plasmapper** [comment]
I think it can depend on the specific Arduino board and chip. For my Arduino Due programming port reset works fine. It is weird that upon power up it works fine for you because it seems that you should expect more power/communication signal issues upon power up than upon reset.
